package VIEW;

import DAO.ClienteDAO;
import DOCUMENT.FixedLengthDocument;
import Entidade.Cliente;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Ademar Zório Neto
 */
public class CadCliente extends javax.swing.JDialog {

    private Entidade.Cliente clienteSelecionado;

    /**
     * Creates new form CadCliente
     */
    public CadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/ICON/sgr.png")).getImage());
        ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));
        ((AbstractDocument) txtEmail.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtEmail));
        ((AbstractDocument) txtEndereco.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtEndereco));
        ((AbstractDocument) txtNumero.getDocument()).setDocumentFilter(new FixedLengthDocument(8, txtNumero));
        ((AbstractDocument) txtBairro.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtBairro));
        ((AbstractDocument) txtComplemento.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtComplemento));
        ((AbstractDocument) txtCidade.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtCidade));
        addEventoTeclaAtalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        txtConsulta = new JTextFieldPersonalizado.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btIncluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateNascimento = new com.toedter.calendar.JDateChooser();
        txtCPF = new JTextFieldPersonalizado.JCFormattedTextField();
        txtRG = new JTextFieldPersonalizado.JCFormattedTextField();
        txtCelular = new JTextFieldPersonalizado.JCFormattedTextField();
        txtTelefone = new JTextFieldPersonalizado.JCFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        txtCep = new JTextFieldPersonalizado.JCFormattedTextField();
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        consultar.setTitle("Consulta");
        consultar.setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta"));

        jLabel17.setText("Filtro");

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "CPF" }));

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText("Consultar");
        btConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultar1MouseClicked(evt);
            }
        });

        txtConsulta.setPlaceholder("Digite aqui para consultar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1))
                .addGap(10, 10, 10))
        );

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaCliente);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText("Selecionar");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionarMouseClicked(evt);
            }
        });

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelar1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelarMouseClicked(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIncluirMouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Cliente"));

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Telefone");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("*CPF");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("*RG");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*Nome Cliente");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("E-mail");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Celular");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("*Dt Nascimento");

        dateNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateNascimentoFocusGained(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRGFocusGained(evt);
            }
        });

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtEmail)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Endereço"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Endereço");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nº");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Bairro");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Complemento");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cidade");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estado");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("CEP");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplemento)))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarMouseClicked(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNovoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNovo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCancelar)
                        .addComponent(btAlterar)
                        .addComponent(btIncluir)
                        .addComponent(btConsultar)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseClicked
        if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cancelar?", "Cancelar", 0) == 0) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        if (btAlterar.isEnabled()) {
            alterar();
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMouseClicked
        incluir();
    }//GEN-LAST:event_btIncluirMouseClicked

    private void btConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarMouseClicked
        Dimension d = new Dimension(515, 390);
        tabelaCliente.getParent().setBackground(new java.awt.Color(233, 232, 230));
        consultar.setSize(d);
        consultar.setPreferredSize(d);
        consultar.setResizable(false);
        consultar.setModal(true);
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        txtConsulta.setText(null);

        tabelaCliente.setModel(new DefaultTableModel());
        setModeloTabela();
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> clientes = clienteDAO.consultarTudoOrdenado();
        carregarTabela(clientes);

        consultar.setVisible(true);
    }//GEN-LAST:event_btConsultarMouseClicked

    private void btNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoMouseClicked
        if (!txtNome.getText().trim().isEmpty() || !txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                || !txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                || !txtTelefone.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", "").isEmpty()
                || !((JTextField) dateNascimento.getDateEditor().getUiComponent()).getText().trim().isEmpty()
                || !txtCelular.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", "").isEmpty() || !txtEmail.getText().trim().isEmpty()
                || !txtEndereco.getText().trim().isEmpty() || !txtNumero.getText().trim().isEmpty()
                || !txtBairro.getText().trim().isEmpty() || !txtComplemento.getText().trim().isEmpty()
                || !txtCidade.getText().trim().isEmpty() || cbEstado.getSelectedIndex() > 0
                || !txtCep.getText().replace("-", "").replace(" ", "").isEmpty()) {

            if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cadastrar um "
                    + "novo cliente?", "Novo", 0) == 0) {
                limpar();
                btAlterar.setEnabled(false);
            }
        } else {
            limpar();
        }
        txtCPF.requestFocus();
    }//GEN-LAST:event_btNovoMouseClicked

    private void btConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultar1MouseClicked
        consultar();
    }//GEN-LAST:event_btConsultar1MouseClicked

    private void btSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseClicked
        if (tabelaCliente.getSelectedRow() != -1) {
            limpar();
            int linha = tabelaCliente.getSelectedRow();
            clienteSelecionado = (Cliente) new ClienteDAO()
                    .consultarPorCpf(tabelaCliente
                            .getModel()
                            .getValueAt(linha, 2)
                            .toString());

            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new DocumentFilter());
            txtNome.setText(tabelaCliente.getModel().getValueAt(linha, 1).toString());
            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));

            txtCPF.setText(tabelaCliente.getModel().getValueAt(linha, 2).toString());

            txtRG.setText(tabelaCliente.getModel().getValueAt(linha, 3).toString());

            Date dt;
            try {
                dt = new SimpleDateFormat("yyyy-MM-dd")
                        .parse(tabelaCliente.getModel().getValueAt(linha, 4).toString());
                dateNascimento.setDate(dt);
            } catch (ParseException ex) {
                Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtTelefone.setText(tabelaCliente.getModel().getValueAt(linha, 5).toString());

            txtCelular.setText(tabelaCliente.getModel().getValueAt(linha, 6).toString());

            ((AbstractDocument) txtEmail.getDocument()).setDocumentFilter(new DocumentFilter());
            txtEmail.setText(tabelaCliente.getModel().getValueAt(linha, 7).toString());
            ((AbstractDocument) txtEmail.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtEmail));

            ((AbstractDocument) txtEndereco.getDocument()).setDocumentFilter(new DocumentFilter());
            txtEndereco.setText(tabelaCliente.getModel().getValueAt(linha, 8).toString());
            ((AbstractDocument) txtEndereco.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtEndereco));

            ((AbstractDocument) txtNumero.getDocument()).setDocumentFilter(new DocumentFilter());
            txtNumero.setText(tabelaCliente.getModel().getValueAt(linha, 9).toString());
            ((AbstractDocument) txtNumero.getDocument()).setDocumentFilter(new FixedLengthDocument(8, txtNumero));

            ((AbstractDocument) txtBairro.getDocument()).setDocumentFilter(new DocumentFilter());
            txtBairro.setText(tabelaCliente.getModel().getValueAt(linha, 10).toString());
            ((AbstractDocument) txtBairro.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtBairro));

            ((AbstractDocument) txtComplemento.getDocument()).setDocumentFilter(new DocumentFilter());
            txtComplemento.setText(tabelaCliente.getModel().getValueAt(linha, 11).toString());
            ((AbstractDocument) txtComplemento.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtComplemento));

            ((AbstractDocument) txtCidade.getDocument()).setDocumentFilter(new DocumentFilter());
            txtCidade.setText(tabelaCliente.getModel().getValueAt(linha, 12).toString());
            ((AbstractDocument) txtCidade.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtCidade));

            cbEstado.setSelectedItem(tabelaCliente.getModel().getValueAt(linha, 13).toString());

            txtCep.setText(tabelaCliente.getModel().getValueAt(linha, 14).toString());
            
            try {
                txtCPF.commitEdit();
                txtRG.commitEdit();
                txtTelefone.commitEdit();
                txtCelular.commitEdit();
                txtCep.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            btAlterar.setEnabled(true);
            consultar.dispose();
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), "Selecione um cliente na tabela"
                    + " antes de pressionar o botão!",
                    "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSelecionarMouseClicked

    private void btCancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar1MouseClicked
        consultar.dispose();
    }//GEN-LAST:event_btCancelar1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btCancelarMouseClicked(null);
    }//GEN-LAST:event_formWindowClosing

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusGained
        txtRG.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtRGFocusGained

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtNomeFocusGained

    private void dateNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateNascimentoFocusGained
        dateNascimento.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dateNascimentoFocusGained

    public void incluir() {
        if (!txtNome.getText().trim().isEmpty() && !txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                && !txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty() && dateNascimento.getDateEditor().getDate() != null) {
            ClienteDAO clienteDAO = new ClienteDAO();
            Entidade.Cliente cliente = new Entidade.Cliente(),
                    cCpf, cRg;
            cCpf = clienteDAO.consultarPorCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (cCpf != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse CPF já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cRg = clienteDAO.consultarPorRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (cRg != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse RG já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cliente.setNomeCliente(txtNome.getText().trim());
            cliente.setCpf(txtCPF.getText().replace(".", "").replace("-", ""));
            cliente.setRg(txtRG.getText().replace(".", "").replace("-", ""));
            cliente.setDtNasc(dateNascimento.getDate());
            cliente.setTelefone(txtTelefone.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", ""));
            cliente.setCelular(txtCelular.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", ""));
            cliente.setEmail(txtEmail.getText());
            cliente.setEndereco(txtEndereco.getText());
            cliente.setNum(txtNumero.getText());
            cliente.setBairro(txtBairro.getText());
            cliente.setComplemento(txtComplemento.getText());
            cliente.setCidade(txtCidade.getText());
            cliente.setCep(txtCep.getText().replace("-", ""));
            if (cbEstado.getSelectedIndex() > 0) {
                cliente.setEstado(cbEstado.getSelectedItem().toString());
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente incluir o "
                        + "cliente?", "Incluir", 0) == 0) {
                    clienteDAO.incluir(cliente);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Cliente incluído com sucesso!");
                    clienteSelecionado = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível incluir o cliente!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao incluir", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            verificaCamposVazios();
        }
    }

    public void consultar() {
        if (!txtConsulta.getText().isEmpty()) {
            ClienteDAO clienteDAO = new ClienteDAO();
            String busca = txtConsulta.getText();
            setModeloTabela();
            tabelaCliente.getParent().setBackground(new java.awt.Color(233, 232, 230));
            List<Entidade.Cliente> clientes = new ArrayList<>();
            if (cbFiltro.getSelectedIndex() == 0) {
                try {
                    Entidade.Cliente c = clienteDAO.consultarPorCodigo(Integer.parseInt(busca));
                    if (c != null) {
                        clientes.add(c);
                    }
                } catch (NumberFormatException erro) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Digite apenas números para o Código!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            } else if (cbFiltro.getSelectedIndex() == 1) {
                try {
                    clientes = clienteDAO.consultarPorNome(busca);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            } else {
                try {
                    Entidade.Cliente c = clienteDAO.consultarPorCpf(busca);
                    if (c != null) {
                        clientes.add(c);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            }
            carregarTabela(clientes);
        } else {
            setModeloTabela();
        }
    }

    public void alterar() {
        if (!txtNome.getText().trim().isEmpty() && !txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                && !txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty() && dateNascimento.getDateEditor().getDate() != null) {
            ClienteDAO clienteDAO = new ClienteDAO();
            Entidade.Cliente cCpf, cRg;
            cCpf = clienteDAO.consultarPorCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (cCpf != null && !clienteSelecionado.getCpf().equals(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse CPF já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cRg = clienteDAO.consultarPorRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (cRg != null && !clienteSelecionado.getRg().equals(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse RG já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            clienteSelecionado.setNomeCliente(txtNome.getText().trim());
            clienteSelecionado.setCpf(txtCPF.getText().replace(".", "").replace("-", ""));
            clienteSelecionado.setRg(txtRG.getText().replace(".", "").replace("-", ""));
            clienteSelecionado.setDtNasc(dateNascimento.getDate());
            clienteSelecionado.setTelefone(txtTelefone.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", ""));
            clienteSelecionado.setCelular(txtCelular.getText().replace("(", "").replace(")", "").replace("-", "").replace(" ", ""));
            clienteSelecionado.setEmail(txtEmail.getText().trim());
            clienteSelecionado.setEndereco(txtEndereco.getText().trim());
            clienteSelecionado.setNum(txtNumero.getText().trim());
            clienteSelecionado.setBairro(txtBairro.getText().trim());
            clienteSelecionado.setComplemento(txtComplemento.getText().trim());
            clienteSelecionado.setCidade(txtCidade.getText().trim());
            clienteSelecionado.setCep(txtCep.getText().replace("-", ""));
            if (cbEstado.getSelectedIndex() > 0) {
                clienteSelecionado.setEstado(cbEstado.getSelectedItem().toString());
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente alterar o "
                        + "cliente?", "Alterar", 0) == 0) {
                    clienteDAO.alterar(clienteSelecionado);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Cliente alterado com sucesso!");
                    clienteSelecionado = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível alterar o cliente!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao alterar", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            verificaCamposVazios();
        }
    }

    private void setModeloTabela() {
        String[] colunas = new String[]{"Código", "Nome", "CPF", "RG", "Dt. Nascimento",
            "Telefone", "Celular", "Email", "Endereço",
            "Número", "Bairro", "Complemento", "Cidade", "Estado", "CEP"};

        DefaultTableModel modelo = new DefaultTableModel(null, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false,
                false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int row, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Class getColumnClass(int col) {
                if (col == 4) {
                    return java.util.Date.class;
                } else {
                    return String.class;
                }
            }

        };
        tabelaCliente.setModel(modelo);
        tabelaCliente.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(73);
        tabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(90);
        tabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(90);
        tabelaCliente.getColumnModel().getColumn(4).setPreferredWidth(90);
        tabelaCliente.getColumnModel().getColumn(5).setPreferredWidth(90);
        tabelaCliente.getColumnModel().getColumn(6).setPreferredWidth(90);
        tabelaCliente.getColumnModel().getColumn(7).setPreferredWidth(150);
        tabelaCliente.getColumnModel().getColumn(8).setPreferredWidth(150);
        tabelaCliente.getColumnModel().getColumn(9).setPreferredWidth(73);
        tabelaCliente.getColumnModel().getColumn(10).setPreferredWidth(120);
        tabelaCliente.getColumnModel().getColumn(11).setPreferredWidth(100);
        tabelaCliente.getColumnModel().getColumn(12).setPreferredWidth(120);
        tabelaCliente.getColumnModel().getColumn(13).setPreferredWidth(73);
        tabelaCliente.getColumnModel().getColumn(14).setPreferredWidth(90);
        tabelaCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void carregarTabela(List<Entidade.Cliente> clientes) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
        for (Entidade.Cliente c : clientes) {
            Object[] linha = new Object[]{
                c.getPkCliente(),
                c.getNomeCliente(),
                c.getCpf(),
                c.getRg(),
                c.getDtNasc(),
                c.getTelefone(),
                c.getCelular(),
                c.getEmail(),
                c.getEndereco(),
                c.getNum(),
                c.getBairro(),
                c.getComplemento(),
                c.getCidade(),
                c.getEstado(),
                c.getCep()
            };
            modelo.addRow(linha);
        }
    }

    private void limpar() {
        try {
            txtCPF.setValue(null);
            txtRG.setValue(null);
            txtNome.getDocument().remove(0, txtNome.getDocument().getLength());
            dateNascimento.setDate(null);
            txtTelefone.setValue(null);
            txtCelular.setValue(null);
            txtEmail.getDocument().remove(0, txtEmail.getDocument().getLength());
            txtEndereco.getDocument().remove(0, txtEndereco.getDocument().getLength());
            txtNumero.getDocument().remove(0, txtNumero.getDocument().getLength());
            txtBairro.getDocument().remove(0, txtBairro.getDocument().getLength());
            txtComplemento.getDocument().remove(0, txtComplemento.getDocument().getLength());
            txtCidade.getDocument().remove(0, txtCidade.getDocument().getLength());
            cbEstado.setSelectedIndex(0);
            txtCep.setValue(null);
            clienteSelecionado = null;
            txtCPF.setBackground(new java.awt.Color(255, 255, 255));
            txtRG.setBackground(new java.awt.Color(255, 255, 255));
            txtNome.setBackground(new java.awt.Color(255, 255, 255));
            dateNascimento.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 255, 255));
        } catch (BadLocationException ex) {
            Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verificaCamposVazios() {
        if (txtNome.getText().trim().isEmpty()) {
            txtNome.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()) {
            txtCPF.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()) {
            txtRG.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (dateNascimento.getDateEditor().getDate() == null) {
            dateNascimento.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 155, 155));
        }
        JOptionPane.showMessageDialog((Frame) getParent(), "Preencha o(s) campo(s) em vermelho!");
    }

    private void addEventoTeclaAtalho() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "Consultar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Consultar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btConsultar.doClick();
                btConsultarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "Novo");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btNovo.doClick();
                btNovoMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Incluir");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Incluir", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btIncluir.doClick();
                btIncluirMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Alterar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Alterar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btAlterar.doClick();
                btAlterarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Cancelar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Cancelar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btCancelar.doClick();
                btCancelarMouseClicked(null);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the SmartLookAndFeel look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadCliente dialog = new CadCliente(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JDialog consultar;
    private com.toedter.calendar.JDateChooser dateNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtBairro;
    private JTextFieldPersonalizado.JCFormattedTextField txtCPF;
    private JTextFieldPersonalizado.JCFormattedTextField txtCelular;
    private JTextFieldPersonalizado.JCFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private JTextFieldPersonalizado.JCTextField txtConsulta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private JTextFieldPersonalizado.JCFormattedTextField txtRG;
    private JTextFieldPersonalizado.JCFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
