package VIEW;

import DAO.CategoriaDAO;
import DOCUMENT.FixedLengthDocument;
import Entidade.Categoria;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Ademar Zório Neto
 */
public class CadCategoria extends javax.swing.JDialog {

    private Entidade.Categoria categoriaSelecionada;

    /**
     * Creates new form CadCategoria
     */
    public CadCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));
        addEventoTeclaAtalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        txtConsulta = new JTextFieldPersonalizado.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategoria = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new JTextFieldPersonalizado.JCTextField();
        cbTipo = new javax.swing.JComboBox<>();
        chControle = new javax.swing.JCheckBox();
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        consultar.setTitle("Consulta");
        consultar.setResizable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta"));

        jLabel17.setText("Filtro");

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Tipo" }));

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText("Consultar");
        btConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultar1MouseClicked(evt);
            }
        });

        txtConsulta.setPlaceholder("Digite aqui para consultar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1))
                .addGap(10, 10, 10))
        );

        tabelaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaCategoria);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText("Selecionar");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionarMouseClicked(evt);
            }
        });

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelar1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Categoria");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIncluirMouseClicked(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelarMouseClicked(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Categoria"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("*Nome Categoria");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*Tipo");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alimento", "Bebida" }));
        cbTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbTipoFocusGained(evt);
            }
        });
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        chControle.setText("Controle de venda");
        chControle.setEnabled(false);
        chControle.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chControle))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipo, 0, 544, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(chControle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarMouseClicked(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNovoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btIncluir)
                        .addComponent(btAlterar)
                        .addComponent(btCancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btNovo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btConsultar)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMouseClicked
        incluir();
    }//GEN-LAST:event_btIncluirMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        if (btAlterar.isEnabled()) {
            alterar();
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        if (cbTipo.getSelectedIndex() == 2) {
            chControle.setEnabled(true);
        } else {
            chControle.setEnabled(false);
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarMouseClicked
        Dimension d = new Dimension(515, 390);
        tabelaCategoria.getParent().setBackground(new java.awt.Color(233, 232, 230));
        consultar.setSize(d);
        consultar.setPreferredSize(d);
        consultar.setResizable(false);
        consultar.setModal(true);
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        txtConsulta.setText(null);

        tabelaCategoria.setModel(new DefaultTableModel());
        setModeloTabela();
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        try {
            List<Categoria> categorias = categoriaDAO.consultarTudoOrdenado();
            carregarTabela(categorias);
            consultar.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getParent(), "Erro ao carregar consulta de categorias!", "Consulta de Categorias", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btConsultarMouseClicked

    private void btNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoMouseClicked
        if (!txtNome.getText().trim().isEmpty() || cbTipo.getSelectedIndex() > 0
                || chControle.isSelected()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cadastrar uma "
                    + "nova categoria?", "Novo", 0) == 0) {
                limpar();
                btAlterar.setEnabled(false);
            }
        } else {
            limpar();
        }
        txtNome.requestFocus();
    }//GEN-LAST:event_btNovoMouseClicked

    private void btConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultar1MouseClicked
        consultar();
    }//GEN-LAST:event_btConsultar1MouseClicked

    private void btSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseClicked
        if (tabelaCategoria.getSelectedRow() != -1) {
            limpar();
            int linha = tabelaCategoria.getSelectedRow();
            categoriaSelecionada = (Categoria) new CategoriaDAO()
                    .consultarPorCodigo(Integer
                            .parseInt(tabelaCategoria
                                    .getModel()
                                    .getValueAt(linha, 0)
                                    .toString()));
            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new DocumentFilter());
            txtNome.setText(tabelaCategoria.getModel().getValueAt(linha, 1).toString());
            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));

            cbTipo.setSelectedItem(tabelaCategoria.getModel().getValueAt(linha, 2).toString());

            if (!tabelaCategoria.getModel().getValueAt(linha, 3).toString().equals("-")) {
                if (tabelaCategoria.getModel().getValueAt(linha, 3).toString().equals("Sim")) {
                    chControle.setSelected(true);
                } else {
                    chControle.setSelected(false);
                }
            }

            btAlterar.setEnabled(true);
            consultar.dispose();
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), "Selecione uma categoria na tabela"
                    + " antes de pressionar o botão!",
                    "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSelecionarMouseClicked

    private void btCancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar1MouseClicked
        consultar.dispose();
    }//GEN-LAST:event_btCancelar1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btCancelarMouseClicked(null);
    }//GEN-LAST:event_formWindowClosing

    private void btCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseClicked
        if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cancelar?", "Cancelar", 0) == 0) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarMouseClicked

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtNomeFocusGained

    private void cbTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoFocusGained
        cbTipo.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_cbTipoFocusGained

    public void incluir() {
        if (!txtNome.getText().trim().isEmpty() && cbTipo.getSelectedIndex() > 0) {
            Entidade.Categoria categoria = new Entidade.Categoria(),
                    cNome;
            cNome = new CategoriaDAO().consultarPorNomeUk(txtNome.getText().trim());
            if (cNome != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse nome já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            categoria.setNomeCategoria(txtNome.getText().trim());
            categoria.setTipo(cbTipo.getSelectedItem().toString());
            if (cbTipo.getSelectedItem().toString().equals("Bebida")) {
                categoria.setControleVenda(chControle.isSelected());
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente incluir a "
                        + "categoria?", "Incluir", 0) == 0) {
                    new CategoriaDAO().incluir(categoria);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Categoria incluída com sucesso!");
                    categoriaSelecionada = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível incluir a categoria!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao incluir", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (txtNome.getText().trim().isEmpty()) {
                txtNome.setBackground(new java.awt.Color(255, 155, 155));
            }
            if (cbTipo.getSelectedIndex() <= 0) {
                cbTipo.setBackground(new java.awt.Color(255, 155, 155));
            }
            JOptionPane.showMessageDialog((Frame) getParent(), "Preencha o(s) campo(s) em vermelho!");
        }
    }

    public void consultar() {
        if (!txtConsulta.getText().isEmpty()) {
            CategoriaDAO categoriaDAO = new CategoriaDAO();
            String busca = txtConsulta.getText();
            setModeloTabela();
            List<Entidade.Categoria> categorias = new ArrayList<>();
            if (cbFiltro.getSelectedIndex() == 0) {
                try {
                    Entidade.Categoria c = categoriaDAO.consultarPorCodigo(Integer.parseInt(busca));
                    if (c != null) {
                        categorias.add(c);
                    }
                } catch (NumberFormatException erro) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Digite apenas números para o Código!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            } else if (cbFiltro.getSelectedIndex() == 1) {
                try {
                    categorias = categoriaDAO.consultarPorNome(busca);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            } else {
                try {
                    categorias = categoriaDAO.consultarPorTipo(busca);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a busca!");
                }
            }
            carregarTabela(categorias);
        } else {
            setModeloTabela();
        }
    }

    public void alterar() {
        if (!txtNome.getText().trim().isEmpty() && cbTipo.getSelectedIndex() > 0) {
            Entidade.Categoria cNome;
            cNome = new CategoriaDAO().consultarPorNomeUk(txtNome.getText().trim());
            if (cNome != null && !categoriaSelecionada.getNomeCategoria().equals(txtNome.getText().trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse nome já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            categoriaSelecionada.setNomeCategoria(txtNome.getText().trim());
            categoriaSelecionada.setTipo(cbTipo.getSelectedItem().toString());
            if (cbTipo.getSelectedItem().toString().equals("Bebida")) {
                categoriaSelecionada.setControleVenda(chControle.isSelected());
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente alterar a "
                        + "categoria?", "Alterar", 0) == 0) {
                    new CategoriaDAO().alterar(categoriaSelecionada);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Categoria alterada com sucesso!");
                    categoriaSelecionada = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível alterar a categoria!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao alterar", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (txtNome.getText().trim().isEmpty()) {
                txtNome.setBackground(new java.awt.Color(255, 155, 155));
            }
            if (cbTipo.getSelectedIndex() <= 0) {
                cbTipo.setBackground(new java.awt.Color(255, 155, 155));
            }
            JOptionPane.showMessageDialog((Frame) getParent(), "Preencha o(s) campo(s) em vermelho!");
        }
    }

    private void setModeloTabela() {
        String[] colunas = new String[]{"Código", "Nome", "Tipo", "Controle de venda"};

        DefaultTableModel modelo = new DefaultTableModel(null, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int row, int columnIndex) {
                return canEdit[columnIndex];
            }

        };
        tabelaCategoria.setModel(modelo);
        tabelaCategoria.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaCategoria.getColumnModel().getColumn(0).setPreferredWidth(73);
        tabelaCategoria.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaCategoria.getColumnModel().getColumn(2).setPreferredWidth(90);
        tabelaCategoria.getColumnModel().getColumn(3).setPreferredWidth(118);
        tabelaCategoria.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void carregarTabela(List<Entidade.Categoria> categorias) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCategoria.getModel();
        for (Entidade.Categoria c : categorias) {
            String controle = "-";
            if (c.getControleVenda() != null) {
                if (c.getControleVenda()) {
                    controle = "Sim";
                } else {
                    controle = "Não";
                }
            }
            Object[] linha = new Object[]{
                c.getPkCategoria(),
                c.getNomeCategoria(),
                c.getTipo(),
                controle
            };
            modelo.addRow(linha);
        }
    }

    private void limpar() {
        try {
            txtNome.getDocument().remove(0, txtNome.getDocument().getLength());
        } catch (BadLocationException ex) {
            Logger.getLogger(CadCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }

        cbTipo.setSelectedIndex(0);
        chControle.setSelected(false);

        categoriaSelecionada = null;
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        cbTipo.setBackground(new java.awt.Color(255, 255, 255));
    }

    private void addEventoTeclaAtalho() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "Consultar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Consultar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btConsultar.doClick();
                btConsultarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "Novo");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btNovo.doClick();
                btNovoMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Incluir");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Incluir", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btIncluir.doClick();
                btIncluirMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Alterar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Alterar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btAlterar.doClick();
                btAlterarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Cancelar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Cancelar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btCancelar.doClick();
                btCancelarMouseClicked(null);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the SmartLookAndFeel look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadCategoria dialog = new CadCategoria(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JCheckBox chControle;
    private javax.swing.JDialog consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCategoria;
    private JTextFieldPersonalizado.JCTextField txtConsulta;
    private JTextFieldPersonalizado.JCTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
