package VIEW;

import DAO.FuncionarioDAO;
import DOCUMENT.FixedLengthDocument;
import Entidade.Funcionario;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Ademar Zório Neto
 */
public class CadFuncionario extends javax.swing.JDialog {

    private Funcionario funcionarioSelecionado;

    /**
     * Creates new form CadFuncionario
     */
    public CadFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/ICON/sgr.png")).getImage());
        txtConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSalario.setFocusLostBehavior(JFormattedTextField.COMMIT);
        ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));
        ((AbstractDocument) txtLogin.getDocument()).setDocumentFilter(new FixedLengthDocument(16, txtLogin));
        ((AbstractDocument) txtSenha.getDocument()).setDocumentFilter(new FixedLengthDocument(16, txtSenha));
        dateContrat.getDateEditor().getUiComponent().addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateContratFocusGained(evt);
            }
        });
        dateContrat.getCalendarButton().addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateContrat.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 255, 255));
            }
        });
        addEventoTeclaAtalho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultar = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbFiltro = new javax.swing.JComboBox<>();
        btConsultar1 = new javax.swing.JButton();
        txtConsulta = new JTextFieldPersonalizado.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        btSelecionar = new javax.swing.JButton();
        btCancelar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dateContrat = new com.toedter.calendar.JDateChooser();
        txtCPF = new JTextFieldPersonalizado.JCFormattedTextField();
        txtRG = new JTextFieldPersonalizado.JCFormattedTextField();
        txtSalario = new JTextFieldPersonalizado.JCFormattedTextField();
        txtNome = new JTextFieldPersonalizado.JCTextField();
        txtLogin = new JTextFieldPersonalizado.JCTextField();
        txtSenha = new JPasswordFieldPersonalizado.JCPasswordField();
        btIncluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btAtiDesat = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        consultar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        consultar.setTitle("Consulta");
        consultar.setResizable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta"));

        jLabel17.setText("Filtro");

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF" }));

        btConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar1.setText("Consultar");
        btConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultar1MouseClicked(evt);
            }
        });

        txtConsulta.setPlaceholder("Digite aqui para consultar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar1))
                .addGap(10, 10, 10))
        );

        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionario);

        btSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_done_18pt.png"))); // NOI18N
        btSelecionar.setText("Selecionar");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionarMouseClicked(evt);
            }
        });

        btCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar1.setText("Cancelar");
        btCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar)
                    .addComponent(btCancelar1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar.getContentPane());
        consultar.getContentPane().setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Funcionário");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Funcionário"));

        jPanel5.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("*Nome Funcionário");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("*CPF");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("*RG");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("*Login");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("*Senha");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("*Cargo");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("*Data Contratação");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("*Status");

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Atendente", "Garçom", "Gerente" }));
        cbCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbCargoFocusGained(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ativo", "Inativo" }));
        cbStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbStatusFocusGained(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Salário");

        dateContrat.setOpaque(false);
        dateContrat.setVerifyInputWhenFocusTarget(false);
        dateContrat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateContratFocusGained(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
        });

        try {
            txtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRGFocusGained(evt);
            }
        });

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
        });

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateContrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_add_18pt.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIncluirMouseClicked(evt);
            }
        });

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_update_18pt.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setEnabled(false);
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        btAtiDesat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_visibility_off_18pt.png"))); // NOI18N
        btAtiDesat.setText("Desativar");
        btAtiDesat.setEnabled(false);
        btAtiDesat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAtiDesatMouseClicked(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_cancel_18pt.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelarMouseClicked(evt);
            }
        });

        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_search_18pt.png"))); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarMouseClicked(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_fiber_new_18pt.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNovoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btAtiDesat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNovo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btIncluir)
                        .addComponent(btAlterar)
                        .addComponent(btAtiDesat)
                        .addComponent(btCancelar)
                        .addComponent(btConsultar)))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIncluirMouseClicked
        incluir();
    }//GEN-LAST:event_btIncluirMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        if (btAlterar.isEnabled()) {
            alterar();
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btAtiDesatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtiDesatMouseClicked
        if (btAtiDesat.isEnabled()) {
            ativarDesativar();
        }
    }//GEN-LAST:event_btAtiDesatMouseClicked

    private void btCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseClicked
        if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cancelar?", "Cancelar", 0) == 0) {
            dispose();
        }
    }//GEN-LAST:event_btCancelarMouseClicked

    private void btConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarMouseClicked
        Dimension d = new Dimension(515, 390);
        tabelaFuncionario.getParent().setBackground(new java.awt.Color(233, 232, 230));
        consultar.setSize(d);
        consultar.setPreferredSize(d);
        consultar.setResizable(false);
        consultar.setModal(true);
        consultar.setLocationRelativeTo(null);
        cbFiltro.setSelectedIndex(0);
        txtConsulta.setText(null);

        tabelaFuncionario.setModel(new DefaultTableModel());
        setModeloTabela();
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionario> funcionarios = funcionarioDAO.consultarTudoOrdenado();
        carregarTabela(funcionarios);

        consultar.setVisible(true);
    }//GEN-LAST:event_btConsultarMouseClicked

    private void btNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoMouseClicked
        if (!txtNome.getText().trim().isEmpty() || !txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                || !txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty() || cbCargo.getSelectedIndex() > 0
                || !((JTextField) dateContrat.getDateEditor().getUiComponent()).getText().isEmpty()
                || !txtLogin.getText().trim().isEmpty() || !txtSenha.getText().isEmpty()
                || cbStatus.getSelectedIndex() > 0 || !txtSalario.getText().trim().isEmpty()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente cadastrar um "
                    + "novo funcionário?", "Novo", 0) == 0) {
                limpar();
                btAlterar.setEnabled(false);
                btAtiDesat.setEnabled(false);
            }
        } else {
            limpar();
        }
        txtCPF.requestFocus();
    }//GEN-LAST:event_btNovoMouseClicked

    private void btConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultar1MouseClicked
        consultar();
    }//GEN-LAST:event_btConsultar1MouseClicked

    private void btSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseClicked
        if (tabelaFuncionario.getSelectedRow() != -1) {
            limpar();
            int linha = tabelaFuncionario.getSelectedRow();
            funcionarioSelecionado = (Funcionario) new FuncionarioDAO()
                    .consultarPorCpf(tabelaFuncionario
                            .getModel()
                            .getValueAt(linha, 2)
                            .toString());

            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new DocumentFilter());
            txtNome.setText(tabelaFuncionario.getModel().getValueAt(linha, 1).toString());
            ((AbstractDocument) txtNome.getDocument()).setDocumentFilter(new FixedLengthDocument(50, txtNome));

            txtCPF.setText(tabelaFuncionario.getModel().getValueAt(linha, 2).toString());
            txtRG.setText(tabelaFuncionario.getModel().getValueAt(linha, 3).toString());
            try {
                txtCPF.commitEdit();
                txtRG.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }


            cbCargo.setSelectedItem(tabelaFuncionario.getModel().getValueAt(linha, 4).toString());
            if (tabelaFuncionario.getModel().getValueAt(linha, 5) != null) {
                txtSalario.setValue(Float.valueOf(tabelaFuncionario.getModel().getValueAt(linha, 5).toString().replace(",", ".")));
            } else {
                txtSalario.setValue(null);
            }
            Date dt;
            try {
                dt = new SimpleDateFormat("yyyy-MM-dd")
                        .parse(tabelaFuncionario.getModel().getValueAt(linha, 6).toString());
                dateContrat.setDate(dt);
            } catch (ParseException ex) {
                Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            cbStatus.setSelectedItem(tabelaFuncionario.getModel().getValueAt(linha, 7).toString());

            ((AbstractDocument) txtLogin.getDocument()).setDocumentFilter(new DocumentFilter());
            txtLogin.setText(tabelaFuncionario.getModel().getValueAt(linha, 8).toString());
            ((AbstractDocument) txtLogin.getDocument()).setDocumentFilter(new FixedLengthDocument(16, txtLogin));

            ((AbstractDocument) txtSenha.getDocument()).setDocumentFilter(new DocumentFilter());
            txtSenha.setText(tabelaFuncionario.getModel().getValueAt(linha, 9).toString());
            ((AbstractDocument) txtSenha.getDocument()).setDocumentFilter(new FixedLengthDocument(16, txtSenha));

            btAlterar.setEnabled(true);
            btAtiDesat.setEnabled(true);
            verificarStatus();
            consultar.dispose();
        } else {
            JOptionPane.showMessageDialog((Frame) getParent(), "Selecione um funcionário na tabela"
                    + " antes de pressionar o botão!",
                    "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSelecionarMouseClicked

    private void btCancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelar1MouseClicked
        consultar.dispose();
    }//GEN-LAST:event_btCancelar1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btCancelarMouseClicked(null);
    }//GEN-LAST:event_formWindowClosing

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusGained
        txtRG.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtRGFocusGained

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_txtSenhaFocusGained

    private void dateContratFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateContratFocusGained
        dateContrat.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_dateContratFocusGained

    private void cbCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCargoFocusGained
        cbCargo.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_cbCargoFocusGained

    private void cbStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbStatusFocusGained
        cbStatus.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_cbStatusFocusGained

    public void incluir() {
        if (!txtNome.getText().trim().isEmpty() && !txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()
                && !txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty() && cbCargo.getSelectedIndex() > 0
                && dateContrat.getDateEditor().getDate() != null && !txtLogin.getText().trim().isEmpty()
                && !txtSenha.getText().isEmpty() && cbStatus.getSelectedIndex() > 0) {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            Funcionario funcionario = new Funcionario(),
                    fCpf, fRg, fLogin;
            fCpf = funcionarioDAO.consultarPorCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (fCpf != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse CPF já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            fRg = funcionarioDAO.consultarPorRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (fRg != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse RG já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            fLogin = funcionarioDAO.consultarPorLogin(txtLogin.getText().trim());
            if (fLogin != null) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse Login já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            funcionario.setNomeFunc(txtNome.getText().trim());
            funcionario.setCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            funcionario.setRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            funcionario.setLogin(txtLogin.getText().trim());
            funcionario.setSenha(txtSenha.getText());
            funcionario.setDtContratacao(dateContrat.getDate());
            if (!txtSalario.getText().isEmpty()) {
                try {
                    funcionario.setSalario(Float.parseFloat(txtSalario.getText().replace(".", "").replace(',', '.')));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Digite um valor válido para o Salário!", "Salário inválido", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            funcionario.setCargo(cbCargo.getSelectedItem().toString());
            if (cbStatus.getSelectedItem().equals("Ativo")) {
                funcionario.setStatus(true);
            } else {
                funcionario.setStatus(false);
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente incluir o "
                        + "funcionário?", "Incluir", 0) == 0) {
                    funcionarioDAO.incluir(funcionario);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Funcionário incluído com sucesso!");
                    funcionarioSelecionado = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    btAtiDesat.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível incluir o funcionário!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao incluir", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            verificarCamposVazios();
        }
    }

    public void consultar() {
        if (!txtConsulta.getText().isEmpty()) {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            String busca = txtConsulta.getText();
            setModeloTabela();
            List<Funcionario> funcionarios = new ArrayList<>();
            if (cbFiltro.getSelectedIndex() == 0) {
                try {
                    funcionarios = funcionarioDAO.consultarPorNome(busca);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a consulta!");
                }
            } else {
                try {
                    Funcionario f = funcionarioDAO.consultarPorCpf(busca);
                    if (f != null) {
                        funcionarios.add(f);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível realizar a consulta!");
                }
            }
            carregarTabela(funcionarios);
        } else {
            setModeloTabela();
        }
    }

    public void alterar() {
        if (!txtNome.getText().trim().isEmpty() && !txtCPF.getText().isEmpty()
                && !txtRG.getText().isEmpty() && cbCargo.getSelectedIndex() > 0
                && dateContrat.getDateEditor().getDate() != null && !txtLogin.getText().trim().isEmpty()
                && !txtSenha.getText().isEmpty() && cbStatus.getSelectedIndex() > 0) {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            Funcionario fCpf, fRg, fLogin;
            fCpf = funcionarioDAO.consultarPorCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (fCpf != null && !funcionarioSelecionado.getCpf().equals(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse CPF já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            fRg = funcionarioDAO.consultarPorRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            if (fRg != null && !funcionarioSelecionado.getRg().equals(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse RG já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            fLogin = funcionarioDAO.consultarPorLogin(txtLogin.getText().trim());
            if (fLogin != null && !funcionarioSelecionado.getLogin().equals(txtLogin.getText().trim())) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Esse Login já existe no sistema!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            funcionarioSelecionado.setNomeFunc(txtNome.getText().trim());
            funcionarioSelecionado.setCpf(txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            funcionarioSelecionado.setRg(txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").trim());
            funcionarioSelecionado.setLogin(txtLogin.getText().trim());
            funcionarioSelecionado.setSenha(txtSenha.getText());
            funcionarioSelecionado.setDtContratacao(dateContrat.getDate());
            if (!txtSalario.getText().isEmpty()) {
                try {
                    funcionarioSelecionado.setSalario(Float.parseFloat(txtSalario.getText().replace(".", "").replace(',', '.')));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Digite um valor válido para o Salário!", "Salário inválido", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            funcionarioSelecionado.setCargo(cbCargo.getSelectedItem().toString());
            if (cbStatus.getSelectedItem().equals("Ativo")) {
                funcionarioSelecionado.setStatus(true);
            } else {
                funcionarioSelecionado.setStatus(false);
            }
            try {
                if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente alterar o "
                        + "funcionário?", "Alterar", 0) == 0) {
                    funcionarioDAO.alterar(funcionarioSelecionado);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Funcionário alterado com sucesso!");
                    funcionarioSelecionado = null;
                    limpar();
                    btAlterar.setEnabled(false);
                    btAtiDesat.setEnabled(false);
                    txtNome.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível alterar o funcionário!\n"
                        + "<html><b>" + e.getClass() + "</html></b>"
                        + "\nContate o desenvolvedor!", "Erro ao alterar", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            verificarCamposVazios();
        }
    }

    public void ativarDesativar() {
        if (btAtiDesat.isSelected()) {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente ativar o "
                    + "funcionário?", "Ativar", 0) == 0) {
                try {
                    funcionarioSelecionado.setStatus(true);
                    new FuncionarioDAO().alterar(funcionarioSelecionado);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Funcionário ativado com sucesso!");
                    cbStatus.setSelectedItem("Ativo");
                    resetFieldColor();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível ativar o funcionário!\n"
                            + "<html><b>" + e.getClass() + "</html></b>"
                            + "\nContate o desenvolvedor!", "Erro ao ativar", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente desativar o "
                    + "funcionário?", "Desativar", 0) == 0) {
                try {
                    funcionarioSelecionado.setStatus(false);
                    new FuncionarioDAO().alterar(funcionarioSelecionado);
                    JOptionPane.showMessageDialog((Frame) getParent(), "Funcionário desativado com sucesso!");
                    cbStatus.setSelectedItem("Inativo");
                    resetFieldColor();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog((Frame) getParent(), "Não foi possível desativar o funcionário!\n"
                            + "<html><b>" + e.getClass() + "</html></b>"
                            + "\nContate o desenvolvedor!", "Erro ao desativar", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        verificarStatus();
    }

    private void setModeloTabela() {
        String[] colunas = new String[]{"Código", "Nome", "CPF", "RG",
            "Cargo", "Salário", "Dt. Contratação", "Status", "Login", "Senha"};
        DefaultTableModel modelo = new DefaultTableModel(null, colunas) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false,
                false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }

            @Override
            public Class getColumnClass(int col) {
                if (col == 6) {
                    return java.util.Date.class;
                } else {
                    return String.class;
                }
            }

        };
        tabelaFuncionario.setModel(modelo);
        tabelaFuncionario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaFuncionario.getColumnModel().getColumn(0).setPreferredWidth(73);
        tabelaFuncionario.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaFuncionario.getColumnModel().getColumn(2).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(3).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(4).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(5).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabelaFuncionario.getColumnModel().getColumn(7).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(8).setPreferredWidth(90);
        tabelaFuncionario.getColumnModel().getColumn(9).setPreferredWidth(90);
        tabelaFuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void carregarTabela(List<Funcionario> funcionarios) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionario.getModel();
        for (Funcionario f : funcionarios) {
            String salario = null;
            if (f.getSalario() != null) {
                salario = f.getSalario().toString().replace('.', ',');
            }
            Object[] linha = new Object[]{
                f.getPkFuncionario(),
                f.getNomeFunc(),
                f.getCpf(),
                f.getRg(),
                f.getCargo(),
                salario,
                f.getDtContratacao(),
                f.getStatus() ? "Ativo" : "Inativo",
                f.getLogin(),
                f.getSenha()
            };
            modelo.addRow(linha);
        }
    }

    private void verificarStatus() {
        if (cbStatus.getSelectedItem().toString().equals("Ativo")) {
            btAtiDesat.setSelected(false);
            btAtiDesat.setText("Desativar");
            btAtiDesat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_visibility_off_18pt.png")));
        } else {
            btAtiDesat.setSelected(true);
            btAtiDesat.setText("Ativar");
            btAtiDesat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_visibility_18pt.png")));
        }
    }

    private void limpar() {
        try {
            txtNome.getDocument().remove(0, txtNome.getDocument().getLength());
            txtCPF.setValue(null);
            txtCPF.setText(null);
            txtRG.setValue(null);
            txtRG.setText(null);
            txtLogin.getDocument().remove(0, txtLogin.getDocument().getLength());
            txtSenha.getDocument().remove(0, txtSenha.getDocument().getLength());
        } catch (BadLocationException ex) {
            Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSalario.setValue(null);
        txtSalario.setText(null);
        cbCargo.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        dateContrat.setDate(null);
        funcionarioSelecionado = null;
        resetFieldColor();
    }

    private void resetFieldColor() {
        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtRG.setBackground(new java.awt.Color(255, 255, 255));
        cbCargo.setBackground(new java.awt.Color(255, 255, 255));
        dateContrat.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 255, 255));
        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        cbStatus.setBackground(new java.awt.Color(255, 255, 255));
    }

    private void verificarCamposVazios() {
        if (txtNome.getText().trim().isEmpty()) {
            txtNome.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()) {
            txtCPF.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtRG.getText().replace(".", "").replace("-", "").replace(" ", "").isEmpty()) {
            txtRG.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (cbCargo.getSelectedIndex() <= 0) {
            cbCargo.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (dateContrat.getDateEditor().getDate() == null) {
            dateContrat.getDateEditor().getUiComponent().setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtLogin.getText().trim().isEmpty()) {
            txtLogin.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (txtSenha.getText().isEmpty()) {
            txtSenha.setBackground(new java.awt.Color(255, 155, 155));
        }
        if (cbStatus.getSelectedIndex() <= 0) {
            cbStatus.setBackground(new java.awt.Color(255, 155, 155));
        }
        JOptionPane.showMessageDialog((Frame) getParent(), "Preencha o(s) campo(s) em vermelho!");
    }

    private void addEventoTeclaAtalho() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "Consultar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Consultar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btConsultar.doClick();
                btConsultarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "Novo");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Novo", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btNovo.doClick();
                btNovoMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), "Incluir");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Incluir", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btIncluir.doClick();
                btIncluirMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), "Alterar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Alterar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btAlterar.doClick();
                btAlterarMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "AtiDesat");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("AtiDesat", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btAtiDesat.doClick();
                btAtiDesatMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "Cancelar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("Cancelar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btCancelar.doClick();
                btCancelarMouseClicked(null);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the SmartLookAndFeel look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadFuncionario dialog = new CadFuncionario(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAtiDesat;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelar1;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btConsultar1;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JDialog consultar;
    private com.toedter.calendar.JDateChooser dateContrat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFuncionario;
    private JTextFieldPersonalizado.JCFormattedTextField txtCPF;
    private JTextFieldPersonalizado.JCTextField txtConsulta;
    private JTextFieldPersonalizado.JCTextField txtLogin;
    private JTextFieldPersonalizado.JCTextField txtNome;
    private JTextFieldPersonalizado.JCFormattedTextField txtRG;
    private JTextFieldPersonalizado.JCFormattedTextField txtSalario;
    private JPasswordFieldPersonalizado.JCPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
