package VIEW;

import Entidade.Funcionario;
import Util.HibernateUtil;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ademar Zório Neto
 */
public class Menu extends javax.swing.JFrame {

    static Funcionario fLogado;
    private String path = null;
    private static final String dbpwd = "";

    /**
     * Creates new form Menu
     */
    protected Menu() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/ICON/sgr.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        try {
            new File(System.getProperty("user.home") + "\\Documents\\Backup de Dados SGR").mkdir();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(getParent(), "Não foi possível criar o diretório\n"
                    + "Backup de Dados SGR!");
        }
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos SQL (*.sql)", "SQL");
        fc.setFileFilter(filtro);
        fc.setAcceptAllFileFilterUsed(false);
        liberarAcesso();
//        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagem/restaurant.jpeg"));
//        int wid = getToolkit().getScreenSize().width;
//        int hei = getToolkit().getScreenSize().height;
////        int hei = Math.round((Float.parseFloat(String.valueOf(wid)) / 4000f) * 3000f);
//        image = image.getScaledInstance(wid, hei, Image.SCALE_SMOOTH);
//        jLabel1.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atalhos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAtalho = new javax.swing.JTextArea();
        sobre = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fc = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuBackup = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenuItem();
        menuEmpresa = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenuItem();
        menuCaixa = new javax.swing.JMenu();
        menuPedidos = new javax.swing.JMenu();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatorioVendas = new javax.swing.JMenuItem();
        menuRelatorioFuncionarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        atalhos.setTitle("Atalhos");
        atalhos.setResizable(false);

        txtAtalho.setEditable(false);
        txtAtalho.setColumns(20);
        txtAtalho.setRows(5);
        txtAtalho.setText("Teclas para a tela do Menu\n----------------------------------------------------------------------------------------------------\nESCAPE - Sair\nCTRL+SHIFT+S - Salvar Backup\nCTRL+SHIFT+O - Restaurar Backup\nCRTL+1 - Categoria\nCRTL+2 - Cliente\nCRTL+3 - Empresa\nCRTL+4 - Funcionário\nCTRL+5 - Produto\nCTRL+6 - Caixa\nCTRL+7 - Pedidos\nCTRL+SHIFT+V - Relatório de Vendas\nCTRL+SHIFT+F - Relatório de Funcionários\n=========================================================\nTeclas para as telas de cadastro\n----------------------------------------------------------------------------------------------------\nESCAPE - Cancelar\nF1 - Consultar\nF2 - Novo\nF3 - Incluir\nF4 - Alterar\nF5 - Ativar/Desativar\nF6 - Confirmar, Emitir\nF7 - Gerar Pedido\nF8 - Adicionar item no pedido\nF9 - Remover item do pedido\nF12 - Imprimir Relatório\nCTRL+Z - Desfazer texto digitado nos campos\nCTRL+Y - Refazer texto digitado nos campos\n=========================================================\nTeclas para a tela de Gerar Pedido\n----------------------------------------------------------------------------------------------------\nESCAPE - Cancelar\nF1 - Consultar\nF2 - Novo\nF7 - Gerar Pedido\nF4 - Alterar\nF8 - Adicionar item no pedido\nF9 - Remover item do pedido\nCTRL+Z - Desfazer texto digitado nos campos\nCTRL+Y - Refazer texto digitado nos campos\n=========================================================\nTeclas para a tela do Caixa\n----------------------------------------------------------------------------------------------------\nESCAPE - Cancelar\nF1 - Consultar\nF6 - Confirmar\n=========================================================\nTeclas para as caixas de diálogo\n----------------------------------------------------------------------------------------------------\nALT+S - Confirmar caixas de diálogo\nALT+N - Negar caixas de diálogo\n=========================================================");
        txtAtalho.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAtalho.setEnabled(false);
        txtAtalho.setFocusable(false);
        txtAtalho.setOpaque(false);
        txtAtalho.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtAtalho);

        javax.swing.GroupLayout atalhosLayout = new javax.swing.GroupLayout(atalhos.getContentPane());
        atalhos.getContentPane().setLayout(atalhosLayout);
        atalhosLayout.setHorizontalGroup(
            atalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atalhosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        atalhosLayout.setVerticalGroup(
            atalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atalhosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        sobre.setTitle("Sobre");
        sobre.setResizable(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo-small.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Desenvolvedores do Sistema");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ademar Zório Neto");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ícones por");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistema de Gerenciamento de Restaurantes");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Beatriz Nascimento Gonçalves Lemes");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Carlos Felipe Almeida Gonçalo");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("José Antônio Gonçalves");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Freepik de www.flaticon.com ");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Google Material Design");

        javax.swing.GroupLayout sobreLayout = new javax.swing.GroupLayout(sobre.getContentPane());
        sobre.getContentPane().setLayout(sobreLayout);
        sobreLayout.setHorizontalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sobreLayout.setVerticalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        setExtendedState(6);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenuBar1.setOpaque(false);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_menu_36pt.png"))); // NOI18N
        jMenu2.setText("Arquivo");

        menuBackup.setText("Backup");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_save_18pt.png"))); // NOI18N
        jMenuItem1.setText("Salvar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuBackup.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ic_settings_backup_restore_18pt.png"))); // NOI18N
        jMenuItem4.setText("Restaurar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuBackup.add(jMenuItem4);

        jMenu2.add(menuBackup);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu2.add(menuSair);

        jMenuBar1.add(jMenu2);

        menuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cadastrar.png"))); // NOI18N
        menuCadastrar.setText("Cadastrar");

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/categoria.png"))); // NOI18N
        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCategoria);

        menuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/cliente.png"))); // NOI18N
        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCliente);

        menuEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        menuEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/empresa.png"))); // NOI18N
        menuEmpresa.setText("Empresa");
        menuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuEmpresa);

        menuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/funcionário.png"))); // NOI18N
        menuFuncionario.setText("Funcionário");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuFuncionario);

        menuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        menuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/produto.png"))); // NOI18N
        menuProduto.setText("Produto");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuProduto);

        jMenuBar1.add(menuCadastrar);

        menuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/caixa.png"))); // NOI18N
        menuCaixa.setText("Caixa");
        menuCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCaixaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCaixa);

        menuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pedidos.png"))); // NOI18N
        menuPedidos.setText("Pedidos");
        menuPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPedidosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPedidos);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/relatórios.png"))); // NOI18N
        menuRelatorios.setText("Relatórios");

        menuRelatorioVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuRelatorioVendas.setText("Vendas");
        menuRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioVendasActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatorioVendas);

        menuRelatorioFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuRelatorioFuncionarios.setText("Funcionários");
        menuRelatorioFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioFuncionariosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatorioFuncionarios);

        jMenuBar1.add(menuRelatorios);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/information.png"))); // NOI18N
        jMenu1.setText("Ajuda");

        jMenuItem2.setText("Atalhos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente sair?", "Sair", 0) == 0) {
            dispose();
        }
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCaixaMouseClicked
        EfetuarPagamento efetuarPagamento = new EfetuarPagamento((Frame) getParent(), true);
        efetuarPagamento.setVisible(true);
    }//GEN-LAST:event_menuCaixaMouseClicked

    private void menuPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPedidosMouseClicked
        GerarPedido pedido = new GerarPedido((Frame) getParent(), true);
        pedido.setVisible(true);
    }//GEN-LAST:event_menuPedidosMouseClicked

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        CadCategoria cadCategoria = new CadCategoria((Frame) getParent(), true);
        cadCategoria.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        CadCliente dCliente = new CadCliente((Frame) getParent(), true);
        dCliente.setVisible(true);
    }//GEN-LAST:event_menuClienteActionPerformed

    private void menuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresaActionPerformed
        CadEmpresa cadEmpresa = new CadEmpresa((Frame) getParent(), true);
        cadEmpresa.setVisible(true);
    }//GEN-LAST:event_menuEmpresaActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        CadFuncionario cadFuncionario = new CadFuncionario((Frame) getParent(), true);
        cadFuncionario.setVisible(true);
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        CadProduto cadProduto = new CadProduto((Frame) getParent(), true);
        cadProduto.setVisible(true);
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void menuRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioVendasActionPerformed
        FiltrarRelatorioVendas filtrarRelatorioVendas = new FiltrarRelatorioVendas(this, true);
        filtrarRelatorioVendas.setVisible(true);
    }//GEN-LAST:event_menuRelatorioVendasActionPerformed

    private void menuRelatorioFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioFuncionariosActionPerformed
        FiltrarRelatorioFuncionarios classificarRelatorioFuncionarios = new FiltrarRelatorioFuncionarios((Frame) getParent(), true);
        classificarRelatorioFuncionarios.setVisible(true);
    }//GEN-LAST:event_menuRelatorioFuncionariosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog((Frame) getParent(), "Deseja realmente sair?", "Sair", 0) == 0) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        salvarBackup();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        restaurarBackup();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        atalhos.setSize(515, 390);
        atalhos.setModal(true);
        atalhos.setResizable(false);
        atalhos.setLocationRelativeTo(null);
        atalhos.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        sobre.setSize(515, 390);
        sobre.setModal(true);
        sobre.setResizable(false);
        sobre.setLocationRelativeTo(null);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void liberarAcesso() {
        if (Menu.fLogado.getCargo().equals("Garçom")) {
            txtAtalho.setText("Teclas para a tela do Menu\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ESCAPE - Sair\n"
                    + "CTRL+7 - Pedidos\n"
                    + "CTRL+SHIFT+V - Relatório de Vendas\n"
                    + "CTRL+SHIFT+F - Relatório de Funcionários\n"
                    + "=========================================================\n"
                    + "Teclas para a tela de Gerar Pedido\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ESCAPE - Cancelar\n"
                    + "F1 - Consultar\n"
                    + "F2 - Novo\n"
                    + "F7 - Gerar Pedido\n"
                    + "F4 - Alterar\n"
                    + "F8 - Adicionar item no pedido\n"
                    + "F9 - Remover item do pedido\n"
                    + "CTRL+Z - Desfazer texto digitado nos campos\n"
                    + "CTRL+Y - Refazer texto digitado nos campos\n"
                    + "=========================================================\n"
                    + "Teclas para as caixas de diálogo\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ALT+S - Confirmar caixas de diálogo\n"
                    + "ALT+N - Negar caixas de diálogo");
            menuBackup.setVisible(false);
            menuCaixa.setVisible(false);
            menuCadastrar.setVisible(false);
            menuRelatorios.setVisible(false);
        } else if (Menu.fLogado.getCargo().equals("Atendente")) {
            txtAtalho.setText("Teclas para a tela do Menu\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ESCAPE - Sair\n"
                    + "CTRL+6 - Caixa\n"
                    + "CTRL+7 - Pedidos\n"
                    + "CTRL+SHIFT+V - Relatório de Vendas\n"
                    + "CTRL+SHIFT+F - Relatório de Funcionários\n"
                    + "=========================================================\n"
                    + "Teclas para a tela de Gerar Pedido\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ESCAPE - Cancelar\n"
                    + "F1 - Consultar\n"
                    + "F2 - Novo\n"
                    + "F7 - Gerar Pedido\n"
                    + "F4 - Alterar\n"
                    + "F8 - Adicionar item no pedido\n"
                    + "F9 - Remover item do pedido\n"
                    + "CTRL+Z - Desfazer texto digitado nos campos\n"
                    + "CTRL+Y - Refazer texto digitado nos campos\n"
                    + "=========================================================\n"
                    + "Teclas para a tela do Caixa\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ESCAPE - Cancelar\n"
                    + "F1 - Consultar\n"
                    + "F6 - Confirmar\n"
                    + "=========================================================\n"
                    + "Teclas para as caixas de diálogo\n"
                    + "----------------------------------------------------------------------------------------------------\n"
                    + "ALT+S - Confirmar caixas de diálogo\n"
                    + "ALT+N - Negar caixas de diálogo");
            menuBackup.setVisible(false);
            menuCategoria.setVisible(false);
            menuEmpresa.setVisible(false);
            menuFuncionario.setVisible(false);
            menuProduto.setVisible(false);
            menuRelatorioFuncionarios.setVisible(false);
        }
    }

    private void salvarBackup() {
        fc.setCurrentDirectory(new File(System.getProperty("user.home") + "\\Documents\\Backup de Dados SGR"));
        String date = new SimpleDateFormat("ddMMyyyyHHmmss").format(new Date());
        fc.setSelectedFile(new File(System.getProperty("user.home") + "\\Documents\\Backup de Dados SGR\\" + "backupSGR_" + date + ".sql"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            try {
                File f = fc.getSelectedFile();
                path = f.getAbsolutePath();
                path = path.replace('\\', '/');
                path = "\"" + path + "\"";
            } catch (Exception e) {
                e.printStackTrace();
            }
            Process p = null;
            try {
                Runtime runtime = Runtime.getRuntime();
                String dbName = "sgr";// database
                String dbHost = "localhost";// host
                String dbPort = "3306";// port
                String dbUserName = "root";// username
                String dbPassword = dbpwd;// Password
                System.out.println(path);
                if (dbPassword.isEmpty()) {
                    p = runtime.exec("C:/xampp/mysql/bin/mysqldump.exe -v -v -v --host=" + dbHost + " --user=" + dbUserName + " --port=" + dbPort + " --protocol=tcp --force --allow-keywords --compress --add-drop-table --default-character-set=binary --hex-blob --databases " + dbName + " --result-file=" + path);
                } else {
                    p = runtime.exec("C:/xampp/mysql/bin/mysqldump.exe -v -v -v --host=" + dbHost + " --user=" + dbUserName + " --password=" + dbPassword + " --port=" + dbPort + " --protocol=tcp --force --allow-keywords --compress --add-drop-table --default-character-set=binary --hex-blob --databases " + dbName + " --result-file=" + path);
                }

                int processComplete = p.waitFor();
                if (processComplete == 0) {
                    JOptionPane.showMessageDialog(getParent(), "Backup salvo com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(getParent(), "Não foi possível salvar o backup!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }

    }

    private void restaurarBackup() {
        fc.setCurrentDirectory(new File(System.getProperty("user.home") + "\\Documents\\Backup de Dados SGR"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            HibernateUtil.getSessionFactory().close();
            try {
                File f = fc.getSelectedFile();
                path = f.getAbsolutePath();
                path = path.replace('\\', '/');
            } catch (Exception e) {
                e.printStackTrace();
            }

            String dbUserName = "root";// username
            String dbPassword = dbpwd;//Password

            String[] restoreCmd;
            if (dbPassword.isEmpty()) {
                //            restoreCmd = "C:/xampp/mysql/bin/mysql.exe --user=" + dbUserName + " < " + path;
                restoreCmd = new String[]{"C:/xampp/mysql/bin/mysql.exe ", "--user=" + dbUserName, "-e", "source " + path};
                System.out.println(restoreCmd);
            } else {
                //            restoreCmd = "C:/xampp/mysql/bin/mysql.exe --user=" + dbUserName + " --password=" + dbPassword + " < " + path;
                restoreCmd = new String[]{"C:/xampp/mysql/bin/mysql.exe ", "--user=" + dbUserName, "--password=" + dbPassword, "-e", "source " + path};
            }
            Process runtimProcess;
            try {
                runtimProcess = Runtime.getRuntime().exec(restoreCmd);
                int proceCom = runtimProcess.waitFor();

                if (proceCom == 0) {
                    JOptionPane.showMessageDialog(getParent(), "Backup restaurado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(getParent(), "Não foi possível restaurar o backup!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            HibernateUtil.createSessionFactory();
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    private void addEventoTeclaAtalho() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_6, InputEvent.CTRL_DOWN_MASK), "MenuCaixa");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("MenuCaixa", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                menuCaixa.doClick();
                menuCaixaMouseClicked(null);
            }
        });
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_7, InputEvent.CTRL_DOWN_MASK), "MenuPedidos");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("MenuPedidos", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                menuPedidos.doClick();
                menuPedidosMouseClicked(null);
            }
        });
    }

    public static void main(String[] args) {
        /* Set the SmartLookAndFeel look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog atalhos;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu menuBackup;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuEmpresa;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenu menuPedidos;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRelatorioFuncionarios;
    private javax.swing.JMenuItem menuRelatorioVendas;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JDialog sobre;
    private javax.swing.JTextArea txtAtalho;
    // End of variables declaration//GEN-END:variables

}
